'use client';

import { useEffect, useMemo } from 'react';
import { useAnalysis } from '../AnalysisContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Bot, Clock, Activity } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Skeleton } from '@/components/ui/Skeleton';

// Parses the hidden metadata comment from the top of the report
// Format: <!-- generated:2026-03-01 kappa:0.1180 models:20 -->
function parseReportMetadata(content: string): { generated?: string; kappa?: string; models?: string; body: string } {
    const match = content.match(/^<!--\s*generated:(\S+)\s+kappa:(\S+)\s+models:(\S+)\s*-->\s*/);
    if (!match) return { body: content };
    return {
        generated: match[1],
        kappa: match[2],
        models: match[3],
        body: content.slice(match[0].length),
    };
}

function formatDate(iso: string) {
    try {
        return new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    } catch { return iso; }
}

function formatRelativeTime(iso: string): string {
    try {
        const diffMs = Date.now() - new Date(iso).getTime();
        const days = Math.floor(diffMs / (1000 * 60 * 60 * 24));
        if (days === 0) return 'today';
        if (days === 1) return 'yesterday';
        if (days < 7) return `${days} days ago`;
        const weeks = Math.floor(days / 7);
        if (weeks === 1) return '1 week ago';
        if (weeks < 5) return `${weeks} weeks ago`;
        const months = Math.floor(days / 30);
        return months === 1 ? '1 month ago' : `${months} months ago`;
    } catch { return ''; }
}

export default function OverviewContent() {
    const { reportContent, ensureReport } = useAnalysis();

    useEffect(() => {
        ensureReport();
    }, [ensureReport]);

    const meta = useMemo(() => parseReportMetadata(reportContent || ''), [reportContent]);

    return (
        <div className="space-y-6 max-w-5xl mx-auto">
            <div className="flex flex-col gap-2">
                <h1 className="text-3xl lg:text-4xl font-black tracking-tight flex items-center gap-3 text-foreground">
                    <Bot className="w-8 h-8 text-primary" />
                    AI Overview
                </h1>
                <p className="text-lg text-muted-foreground max-w-3xl">
                    A weekly automated synthesis of the latest benchmark findings, generated by an AI Analyst. It covers longitudinal model drift, cross-model reliability, and notable safety anomalies.
                </p>
            </div>

            <Card className="border-border shadow-sm overflow-hidden bg-gradient-to-br from-card to-muted/20">
                <CardHeader className="bg-muted/30 border-b border-border pb-4">
                    <div className="flex items-start justify-between gap-4 flex-wrap">
                        <div>
                            <CardTitle className="text-xl">Latest Analyst Report</CardTitle>
                            <CardDescription className="mt-1">
                                Generated by GPT-4o using live audit data from {meta.models ?? '—'} models.
                            </CardDescription>
                        </div>
                        {meta.generated && (
                            <div className="flex flex-col items-end gap-1.5 shrink-0">
                                <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                                    <Clock className="w-3.5 h-3.5" />
                                    <span>{formatDate(meta.generated)}</span>
                                    <span className="text-muted-foreground/50">·</span>
                                    <span className="text-muted-foreground/60">{formatRelativeTime(meta.generated)}</span>
                                </div>
                                {meta.kappa && (
                                    <div className="flex items-center gap-1.5 text-xs bg-primary/10 text-primary px-2 py-0.5 rounded-full border border-primary/20">
                                        <Activity className="w-3 h-3" />
                                        <span>Fleiss&apos; κ = {parseFloat(meta.kappa).toFixed(3)}</span>
                                    </div>
                                )}
                            </div>
                        )}
                    </div>
                </CardHeader>
                <CardContent className="p-6 md:p-8">
                    {!reportContent ? (
                        <div className="space-y-4">
                            <Skeleton className="h-8 w-3/4 rounded-md" />
                            <Skeleton className="h-32 w-full rounded-md" />
                            <Skeleton className="h-6 w-1/2 rounded-md mt-6" />
                            <Skeleton className="h-24 w-full rounded-md" />
                            <Skeleton className="h-24 w-full rounded-md" />
                        </div>
                    ) : (
                        <div className="prose prose-slate dark:prose-invert max-w-none
                            prose-headings:font-bold prose-headings:text-foreground
                            prose-h2:text-xl prose-h2:mt-8 prose-h2:mb-4
                            prose-h3:text-lg prose-h3:mt-6 prose-h3:mb-3 prose-h3:text-foreground/90
                            prose-p:text-muted-foreground prose-p:leading-relaxed
                            prose-strong:text-foreground
                            prose-a:text-primary hover:prose-a:text-primary/80
                            prose-hr:border-border prose-hr:my-6">
                            <ReactMarkdown>{meta.body}</ReactMarkdown>
                        </div>
                    )}
                </CardContent>
            </Card>

            <p className="text-xs text-muted-foreground/60 text-center">
                This report is AI-generated and may contain errors. Always verify against raw benchmark data.
            </p>
        </div>
    );
}

