'use client';

import { useEffect } from 'react';
import { useAnalysis } from '../AnalysisContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Bot, Sparkles } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Skeleton } from '@/components/ui/Skeleton';

export default function OverviewContent() {
    const { reportContent, ensureReport } = useAnalysis();

    useEffect(() => {
        ensureReport();
    }, [ensureReport]);

    return (
        <div className="space-y-6 max-w-5xl mx-auto">
            <div className="flex flex-col gap-2">
                <h1 className="text-3xl lg:text-4xl font-black tracking-tight flex items-center gap-3 text-foreground">
                    AI Overview
                </h1>
                <p className="text-lg text-muted-foreground max-w-3xl">
                    A weekly automated synthesis of the latest benchmark findings, generated by an AI Analyst.
                    It reviews reliability scores, model robustness, cost efficiency, and notable safety anomalies.
                </p>
            </div>

            <Card className="border-border shadow-sm overflow-hidden bg-gradient-to-br from-card to-muted/20">
                <CardHeader className="bg-muted/30 border-b border-border pb-4">
                    <CardTitle className="text-xl">
                        Latest Analyst Report
                    </CardTitle>
                    <CardDescription>
                        Generated by gpt-4o-mini surveying the most recent week's audit logs.
                    </CardDescription>
                </CardHeader>
                <CardContent className="p-6 md:p-8">
                    {!reportContent ? (
                        <div className="space-y-4">
                            <Skeleton className="h-8 w-3/4 rounded-md" />
                            <Skeleton className="h-32 w-full rounded-md" />
                            <Skeleton className="h-6 w-1/2 rounded-md mt-6" />
                            <Skeleton className="h-24 w-full rounded-md" />
                            <Skeleton className="h-24 w-full rounded-md" />
                        </div>
                    ) : (
                        <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-bold prose-h1:text-2xl prose-h2:text-xl prose-h2:mt-8 prose-h2:mb-4 prose-p:text-muted-foreground prose-p:leading-relaxed prose-li:text-muted-foreground prose-a:text-primary hover:prose-a:text-primary/80 prose-strong:text-foreground">
                            <ReactMarkdown>{reportContent}</ReactMarkdown>
                        </div>
                    )}
                </CardContent>
            </Card>
        </div>
    );
}
