/**
 * Ensure the audit CSV data files are present in public/ before dev/build.
 *
 * The CSVs are gitignored (regenerated by the audit pipeline and stored on
 * Vercel Blob), so a fresh checkout / CI build won't have them. This script
 * downloads the full and lite gzipped CSVs from Blob if they're missing.
 *
 * NOTE: This previously also generated a ~290MB public/assets/traces.json that
 * nothing ever read (the only reader was a dead `useTraces` branch). That was
 * deployed and served publicly on every build — pure waste — and has been
 * removed.
 */
const fs = require('fs');
const path = require('path');

const BLOB_BASE = 'https://oeqbf51ent3zxva1.public.blob.vercel-storage.com/data';
const PUBLIC_DIR = path.join(__dirname, '..', 'public');

const FILES = [
    { name: 'audit_log.csv.gz', url: `${BLOB_BASE}/audit_log.csv.gz` },
    { name: 'audit_log_lite.csv.gz', url: `${BLOB_BASE}/audit_log_lite.csv.gz` },
];

async function ensureFile({ name, url }) {
    const dest = path.join(PUBLIC_DIR, name);
    if (fs.existsSync(dest)) {
        console.log(`✓ ${name} already present`);
        return;
    }
    console.log(`⬇️  Downloading ${name} from Blob...`);
    const response = await fetch(url);
    if (!response.ok) {
        throw new Error(`Failed to fetch ${name}: ${response.status} ${response.statusText}`);
    }
    const buffer = Buffer.from(await response.arrayBuffer());
    fs.mkdirSync(PUBLIC_DIR, { recursive: true });
    fs.writeFileSync(dest, buffer);
    console.log(`✅ Downloaded ${name} (${(buffer.length / 1024 / 1024).toFixed(2)} MB)`);
}

async function main() {
    try {
        for (const file of FILES) {
            await ensureFile(file);
        }
    } catch (error) {
        console.error('❌ prepare-data failed:', error);
        process.exit(1);
    }
}

main();
